import { useState, useEffect, useRef } from 'react'
import { useParams, Link } from 'react-router-dom'
import ReactMarkdown from 'react-markdown'
import remarkGfm from 'remark-gfm'
import { getLectureById, LECTURES } from '../data/lectures'
import { chatWithTutor } from '../services/geminiService'
import styles from './LecturePage.module.css'

export default function LecturePage() {
  const { id } = useParams()
  const lectureMeta = getLectureById(id)
  
  const [lectureData, setLectureData] = useState(null)
  const [loading, setLoading] = useState(true)
  const [currentSlideIdx, setCurrentSlideIdx] = useState(0)
  const [activeTab, setActiveTab] = useState('notes') // 'notes' | 'tutor'
  
  // AI Tutor Chat state
  const [chatMessages, setChatMessages] = useState([])
  const [chatInput, setChatInput] = useState('')
  const [sendingChat, setSendingChat] = useState(false)
  const messagesEndRef = useRef(null)

  // Dynamically load the lecture JSON file generated by python extraction
  useEffect(() => {
    setLoading(true)
    setCurrentSlideIdx(0)
    setChatMessages([
      {
        sender: 'bot',
        text: `Hi! I'm your Antigravity AI Tutor. Ask me anything about Dr. Moheeb's lecture: "${lectureMeta?.title || 'this lecture'}".`
      }
    ])
    
    import(`../data/lectures/lec${id}.json`)
      .then(res => {
        setLectureData(res.default)
        setLoading(false)
      })
      .catch(err => {
        console.error("Failed to load lecture JSON data:", err)
        setLoading(false)
      })
  }, [id, lectureMeta])

  // Scroll chat messages to bottom
  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' })
  }, [chatMessages])

  if (!lectureMeta) {
    return (
      <div className={styles.container}>
        <div className={styles.noNotes}>Lecture not found</div>
      </div>
    )
  }

  if (loading) {
    return (
      <div className={styles.container}>
        <div className={styles.loading}>
          <div className={styles.spinner}></div>
          <p>Extracting slide deck content...</p>
        </div>
      </div>
    )
  }

  const slides = lectureData?.slides || []
  const currentSlide = slides[currentSlideIdx]
  
  // Navigation
  const prevSlide = () => setCurrentSlideIdx(i => Math.max(0, i - 1))
  const nextSlide = () => setCurrentSlideIdx(i => Math.min(slides.length - 1, i + 1))
  
  // Lecture Links
  const prevLecture = LECTURES.find(l => l.number === lectureMeta.number - 1)
  const nextLecture = LECTURES.find(l => l.number === lectureMeta.number + 1)

  // Key navigation for slides
  const handleKeyDown = (e) => {
    if (e.key === 'ArrowLeft') prevSlide()
    if (e.key === 'ArrowRight') nextSlide()
  }

  // Handle AI Tutor Chat Send
  const handleSendChat = async (e) => {
    e.preventDefault()
    if (!chatInput.trim() || sendingChat) return

    const userMsg = chatInput.trim()
    setChatInput('')
    setChatMessages(prev => [...prev, { sender: 'user', text: userMsg }])
    setSendingChat(true)

    // Build context details for this specific slide
    const context = {
      lectureTitle: lectureMeta.title,
      slideNum: currentSlide?.slideNumber || (currentSlideIdx + 1),
      slideTitle: currentSlide?.title || '',
      slideContent: currentSlide?.content || [],
      ocrContent: currentSlide?.ocrContent || '',
      speakerNotes: currentSlide?.notes || ''
    }

    try {
      const response = await chatWithTutor(context, userMsg, chatMessages)
      setChatMessages(prev => [...prev, { sender: 'bot', text: response }])
    } catch (err) {
      setChatMessages(prev => [
        ...prev, 
        { sender: 'bot', text: `Sorry, I encountered an error: ${err.message || 'Unknown network error'}. Please try again.` }
      ])
    } finally {
      setSendingChat(false)
    }
  }

  // Helper to build correct image URL with base path support
  const getImageUrl = (path) => {
    if (!path) return ''
    const base = import.meta.env.BASE_URL || '/'
    return base + path.replace(/^\//, '')
  }

  return (
    <div className={styles.container} onKeyDown={handleKeyDown} tabIndex="0">
      <div className={styles.mainLayout}>
        {/* Left: Slide Viewer */}
        <div className={styles.viewerPane}>
          <div className={styles.slideContainer}>
            {slides.length === 0 ? (
              <div className={styles.noNotes}>No slides found in this lecture.</div>
            ) : (
              <div className={styles.slideCard}>
                <div className={styles.slideHeader}>
                  <h2 className={styles.slideTitle}>
                    {currentSlide?.title || `Slide ${currentSlide?.slideNumber}`}
                  </h2>
                  <span className={styles.slideNumBadge}>
                    Slide {currentSlideIdx + 1} of {slides.length}
                  </span>
                </div>

                <div className={styles.slideBody}>
                  {/* Display Slide Images if available (especially for text-light or screenshots) */}
                  {currentSlide?.images && currentSlide.images.length > 0 ? (
                    <div className={styles.slideImageWrap}>
                      <img 
                        src={getImageUrl(currentSlide.images[0])} 
                        alt={`Slide ${currentSlideIdx + 1}`} 
                        className={styles.slideImage} 
                      />
                    </div>
                  ) : (
                    /* Otherwise fallback to text list formatting */
                    <ul className={styles.bulletList}>
                      {currentSlide?.content?.map((bullet, idx) => (
                        <li key={idx} className={styles.bulletItem}>
                          {bullet}
                        </li>
                      ))}
                      {(!currentSlide?.content || currentSlide.content.length === 0) && (
                        <p className={styles.noNotes}>Empty Slide Content</p>
                      )}
                    </ul>
                  )}
                </div>
              </div>
            )}
          </div>

          {/* Bottom Controls Bar */}
          <div className={styles.controlsBar}>
            <div className={styles.navBtnGroup}>
              <button 
                onClick={prevSlide} 
                disabled={currentSlideIdx === 0}
                className="btn btn-outline"
              >
                ◀ Prev Slide
              </button>
              <button 
                onClick={nextSlide} 
                disabled={currentSlideIdx === slides.length - 1}
                className="btn btn-primary"
              >
                Next Slide ▶
              </button>
            </div>

            <span className={styles.slideProgress}>
              Slide {currentSlideIdx + 1} / {slides.length}
            </span>

            <div className={styles.navBtnGroup}>
              {prevLecture && (
                <Link to={`/lecture/${prevLecture.id}`} className="btn btn-outline">
                  ◀ Previous Lecture
                </Link>
              )}
              {nextLecture && (
                <Link to={`/lecture/${nextLecture.id}`} className="btn btn-outline">
                  Next Lecture ▶
                </Link>
              )}
            </div>
          </div>
        </div>

        {/* Right: Notes / AI Tutor */}
        <div className={styles.detailsPane}>
          <div className={styles.tabsHeader}>
            <button 
              className={`${styles.tabBtn} ${activeTab === 'notes' ? styles.tabBtnActive : ''}`}
              onClick={() => setActiveTab('notes')}
            >
              📝 Speaker Notes
            </button>
            <button 
              className={`${styles.tabBtn} ${activeTab === 'tutor' ? styles.tabBtnActive : ''}`}
              onClick={() => setActiveTab('tutor')}
            >
              🤖 Ask AI Tutor
            </button>
          </div>

          <div className={styles.tabContent}>
            {activeTab === 'notes' ? (
              <div>
                <h3 className={styles.notesTitle}>
                  <span>💡</span> Slide Notes & Context
                </h3>
                {currentSlide?.notes ? (
                  <div className={styles.notesBody}>
                    <ReactMarkdown remarkPlugins={[remarkGfm]}>
                      {currentSlide.notes}
                    </ReactMarkdown>
                  </div>
                ) : (
                  <div className={styles.noNotes}>
                    No speaker notes available for this slide.
                  </div>
                )}

                {/* Show OCR Text if slide is a screenshot and OCR exists */}
                {currentSlide?.ocrContent && (
                  <div style={{ marginTop: '20px', borderTop: '1px solid var(--border-subtle)', paddingTop: '16px' }}>
                    <h4 className={styles.ocrHeader}>OCR Extracted Slide Text</h4>
                    <div className={styles.notesBody} style={{ whiteSpace: 'pre-line', fontStyle: 'italic', color: 'var(--text-secondary)' }}>
                      {currentSlide.ocrContent.replace(/\[OCR_SKIPPED.*?\]/, 'No OCR text available.')}
                    </div>
                  </div>
                )}
              </div>
            ) : (
              <div className={styles.chatArea}>
                <div className={styles.chatMessages}>
                  {chatMessages.map((msg, idx) => (
                    <div 
                      key={idx} 
                      className={`${styles.message} ${msg.sender === 'user' ? styles.messageUser : styles.messageBot}`}
                    >
                      <span className={`${styles.messageSender} ${msg.sender === 'user' ? styles.messageSenderUser : styles.messageSenderBot}`}>
                        {msg.sender === 'user' ? 'Student' : 'AI Tutor'}
                      </span>
                      <div className="markdown-body" style={{ color: 'inherit' }}>
                        <ReactMarkdown remarkPlugins={[remarkGfm]}>
                          {msg.text}
                        </ReactMarkdown>
                      </div>
                    </div>
                  ))}
                  <div ref={messagesEndRef} />
                </div>

                <form onSubmit={handleSendChat} className={styles.chatInputArea}>
                  <input
                    type="text"
                    value={chatInput}
                    onChange={(e) => setChatInput(e.target.value)}
                    placeholder="Ask about this slide..."
                    className={styles.chatInput}
                    disabled={sendingChat}
                  />
                  <button 
                    type="submit" 
                    className={styles.sendBtn}
                    disabled={!chatInput.trim() || sendingChat}
                  >
                    {sendingChat ? '...' : '➔'}
                  </button>
                </form>
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  )
}
